from pydantic import BaseModel, Field
from datetime import datetime
from typing import List, Optional, Dict, Any

class SessionCreate(BaseModel):
    """Schema for creating a new session."""
    session_id: str = Field(..., description="UUID generated by the frontend")
    title: str = Field(default="New Chat")

class SessionUpdate(BaseModel):
    """Schema for updating the session title."""
    title: str

class SessionHeader(BaseModel):
    """Session header for the Sidebar list."""
    session_id: str
    title: str
    last_update: datetime
    created_at: Optional[datetime] = None

    class Config:
        from_attributes = True

class SessionDetail(SessionHeader):
    """Full session data including message history."""
    messages: List[Dict[str, Any]] = Field(default_factory=list)